<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2013/07/19 08:18:33
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrineroutecollection' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineroute' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrinecli' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrinecolumn' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformgenerator' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrineformfiltergenerator' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrinegenerator' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'swift_doctrinespool' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sftesterdoctrine' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfformdoctrine' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinepager' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfwebdebugpaneldoctrine' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfvalidatordoctrinechoice' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfdoctrinemigratetask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinebuildschematask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinedataloadtask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinebuildformstask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinebuildtask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinegenerateadmintask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinebuildmodeltask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildfilterstask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinedropdbtask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinedqltask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedatadumptask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinecreatemodeltables' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinebuildsqltask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrineinsertsqltask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinebuilddbtask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinebasetask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrineexception' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinedatabase' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrineconnectionprofiler' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrineconnectionlistener' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrinerecordi18nfilter' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrinerecord' => '/home/prabhu/Projects/jobeet/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',

  // project
  'baseform' => '/home/prabhu/Projects/jobeet/lib/form/BaseForm.class.php',
  'jobeetaffiliateform' => '/home/prabhu/Projects/jobeet/lib/form/doctrine/JobeetAffiliateForm.class.php',
  'basejobeetcategoryaffiliateform' => '/home/prabhu/Projects/jobeet/lib/form/doctrine/base/BaseJobeetCategoryAffiliateForm.class.php',
  'basejobeetjobform' => '/home/prabhu/Projects/jobeet/lib/form/doctrine/base/BaseJobeetJobForm.class.php',
  'basejobeetaffiliateform' => '/home/prabhu/Projects/jobeet/lib/form/doctrine/base/BaseJobeetAffiliateForm.class.php',
  'basejobeetcategoryform' => '/home/prabhu/Projects/jobeet/lib/form/doctrine/base/BaseJobeetCategoryForm.class.php',
  'jobeetcategoryform' => '/home/prabhu/Projects/jobeet/lib/form/doctrine/JobeetCategoryForm.class.php',
  'jobeetjobform' => '/home/prabhu/Projects/jobeet/lib/form/doctrine/JobeetJobForm.class.php',
  'baseformdoctrine' => '/home/prabhu/Projects/jobeet/lib/form/doctrine/BaseFormDoctrine.class.php',
  'jobeetcategoryaffiliateform' => '/home/prabhu/Projects/jobeet/lib/form/doctrine/JobeetCategoryAffiliateForm.class.php',

  // project_model
  'jobeetjobtable' => '/home/prabhu/Projects/jobeet/lib/model/doctrine/JobeetJobTable.class.php',
  'basejobeetjob' => '/home/prabhu/Projects/jobeet/lib/model/doctrine/base/BaseJobeetJob.class.php',
  'basejobeetcategoryaffiliate' => '/home/prabhu/Projects/jobeet/lib/model/doctrine/base/BaseJobeetCategoryAffiliate.class.php',
  'basejobeetaffiliate' => '/home/prabhu/Projects/jobeet/lib/model/doctrine/base/BaseJobeetAffiliate.class.php',
  'basejobeetcategory' => '/home/prabhu/Projects/jobeet/lib/model/doctrine/base/BaseJobeetCategory.class.php',
  'jobeetcategoryaffiliate' => '/home/prabhu/Projects/jobeet/lib/model/doctrine/JobeetCategoryAffiliate.class.php',
  'jobeetjob' => '/home/prabhu/Projects/jobeet/lib/model/doctrine/JobeetJob.class.php',
  'jobeetcategoryaffiliatetable' => '/home/prabhu/Projects/jobeet/lib/model/doctrine/JobeetCategoryAffiliateTable.class.php',
  'jobeetaffiliate' => '/home/prabhu/Projects/jobeet/lib/model/doctrine/JobeetAffiliate.class.php',
  'jobeetcategorytable' => '/home/prabhu/Projects/jobeet/lib/model/doctrine/JobeetCategoryTable.class.php',
  'jobeetcategory' => '/home/prabhu/Projects/jobeet/lib/model/doctrine/JobeetCategory.class.php',
  'jobeetaffiliatetable' => '/home/prabhu/Projects/jobeet/lib/model/doctrine/JobeetAffiliateTable.class.php',

  // application
  'myuser' => '/home/prabhu/Projects/jobeet/apps/frontend/lib/myUser.class.php',

  // modules
);
