<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/07/26 12:09:12

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
