<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/07/26 12:16:49
$this->security = array (
  'index' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'admin',
  ),
);
